### ISSUE TITLE
Can not close camera

### ISSUE THREAD

**Issue by Oza-Jeetkumar-Vishnubhai** [lauirvin/react-use-face-detection-demo#2]
The webcamref that is being received from hook can not close the video stream using webcamref.current.stream.getTracks()[0].stop()
If I use webcamref=useref(null) it is closing with react-web but not the one which is being received from hook.

**Comment by sharpcodes19wf** [comment]
did you fixed this issue?

**Comment by lauirvin** [comment]
Related to: https://github.com/lauirvin/react-use-face-detection/issues/3
